// HTML output builder for raw scraper results
import type { ScrapedArticle } from "./types";

function esc(s: string): string {
  return String(s ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function renderArticle(a: ScrapedArticle): string {
  const tags = (a.tags ?? [])
    .map((t) => `<span style="display:inline-block;background:#e2e8f0;color:#475569;font-size:10px;padding:2px 8px;border-radius:999px;margin-right:4px;">${esc(t)}</span>`)
    .join("");
  return `<article style="border:1px solid #e2e8f0;border-radius:12px;padding:16px;margin:12px 0;background:#fff;">
    <div style="font-size:11px;color:#64748b;text-transform:uppercase;letter-spacing:.05em;margin-bottom:6px;">
      ${esc(a.source)} · score ${a.score}
    </div>
    <h3 style="margin:0 0 8px;font-size:17px;line-height:1.3;">
      <a href="${esc(a.url)}" style="color:#1F3864;text-decoration:none;">${esc(a.title)}</a>
    </h3>
    ${a.author ? `<p style="margin:0 0 6px;font-size:12px;color:#64748b;">by ${esc(a.author)}</p>` : ""}
    <p style="margin:0;font-size:13px;color:#334155;line-height:1.5;">${esc(a.description)}</p>
    ${tags ? `<div style="margin-top:8px;">${tags}</div>` : ""}
  </article>`;
}

export function buildScrapersHtml(
  sections: Array<{ name: string; articles: ScrapedArticle[] }>,
  date: string,
): string {
  const total = sections.reduce((n, s) => n + s.articles.length, 0);
  const body = sections
    .map(
      (s) =>
        `<section style="margin-bottom:28px;">
          <h2 style="font-size:20px;color:#0f172a;border-bottom:2px solid #1F3864;padding-bottom:6px;margin-bottom:12px;">
            ${esc(s.name)} <span style="font-size:13px;color:#64748b;font-weight:normal;">(${s.articles.length})</span>
          </h2>
          ${s.articles.map(renderArticle).join("")}
        </section>`,
    )
    .join("");

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width,initial-scale=1"/>
  <title>InsightSenderBot Scraper Report · ${esc(date)}</title>
</head>
<body style="margin:0;padding:0;background:#f8fafc;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Inter,Arial,sans-serif;">
  <div style="max-width:720px;margin:0 auto;padding:28px 20px;">
    <header style="margin-bottom:24px;">
      <div style="font-size:11px;font-weight:700;letter-spacing:.1em;text-transform:uppercase;color:#64748b;">
        Web Scraper Report
      </div>
      <h1 style="margin:6px 0 0;font-size:26px;color:#0f172a;">InsightSenderBot · ${esc(date)}</h1>
      <p style="margin:6px 0 0;color:#64748b;font-size:13px;">
        ${total} items from yt-dlp · webScrapers · keep-up-daily · TrendingNews
      </p>
    </header>
    ${body}
    <footer style="color:#94a3b8;font-size:11px;margin-top:32px;text-align:center;">
      Generated by InsightSenderBot default scrapers
    </footer>
  </div>
</body>
</html>`;
}
